name: Run tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

  merge_group:
    types: [checks_requested]

jobs:
  test:
    runs-on: namespace-profile-e2e
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: false

      - name: Setup runner cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go

      - name: Test
        run: go test ./...
